# Generated by Django 2.2.11 on 2020-03-26 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numexp', models.SmallIntegerField()),
                ('anio', models.SmallIntegerField()),
                ('quejoso', models.TextField()),
                ('fecarc', models.DateTimeField()),
                ('tipo', models.CharField(max_length=3)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
