# Generated by Django 2.2.11 on 2020-03-26 04:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecarc',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
